[pytest]
# 1. Point to your main Django settings folder name (replace 'my_project' with yours)
DJANGO_SETTINGS_MODULE = core.settings

# 2. Tell pytest to search all folders for these specific test filenames
python_files = tests.py test_*.py *_tests.py
