apiVersion: v1
kind: ConfigMap
metadata:
  name: banner-app-config
  namespace: banners-main-app
  labels:
    environment: production
    app.kubernetes.io/name: banners-main-app-deployments
    app.kubernetes.io/part-of: banners-main-app
immutable: true       # fixed

data:
  DEBUG: "True"

  # this is onetype of gunicorn conf from outside instead of doing from image, means if we want to change the 
  # guni timing then we need to go to the source code change file them again build image, agin it will go via tests and all
  gunicorn.conf.py: |
    import multiprocessing
    workers = multiprocessing.cpu_count() * 2 + 1
    bind = "0.0.0.0:8080"
    timeout = 120
    accesslog = "-"
    errorlog = "-"
    worker_class = "gevent"
