apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: banners-rds-sync
  namespace: banners-main-app
spec:
  refreshInterval: 1h           # check for change every 1h

  secretStoreRef:
    name: global-banner-secrets
    kind: ClusterSecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
    deletionPolicy: Retain      # secrets isnt deleted if file deleted, keeping app online

    template: 
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://{{ .db_user }}:{{ .db_password }}@{{ .db_host }}:{{ .db_port }}/{{ .db_name }}"

        # pass this also if settings.py prefers them
        #DB_USER: "{{ .db_user }}"
        #DB_PASSWORD: "{{ .db_password }}"
        DEBUG: True
        SECRET_KEY: "{{ .secret-key }}"

  data:
    - secretKey: db_user
      remoteRef:
        key: production/ban-rds/credentials
        property: username
    - secretKey: db_password
      remoteRef:
        key: production/ban-rds/credentials
        property: password
    - secretRef: db_host
      remoteRef:
        key: production/ban-rds/credentials
        property: host
    - secretRef: db_port
      remoteRef: 
        key: production/ban-rds/credentials
        property: port
    - secretRef: db_name
      remoteRef:
        key: production/ban-rds/credentials
        property: dbname
    - secretRef: secret-key
      remoteRef:
        key: production/ban-rds/credentials
        property: secret-key
