#dynamically we can kustomize the yaml parameters like updated images... etc
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    environment: production
    app.kubernetes.io/name: banners-main-app-deployments
    app.kubernetes.io/part-of: banners-main-app
  name: banner-kustomize
  namespace: banners-main-app
resources:
  - alerts-prom.yaml
  - configmap.yaml
  - deployments.yaml
  - externalsecrets.yaml
  - ingress.yaml
  - namespace.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - podautoscaler.yaml
  - service.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
images:
- name: banners-django-container
  newName: banners-pythonapp-repo
  newTag: v1.0.1
