"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import sys
import os, environ
import dj_database_url
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(
    # Set default values and casting
    DEBUG=(bool, False)
)

# Tell environ where to find the .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*','localhost','127.0.0.1','.vercel.app','shirdihoarding.in']


# Application definition

INSTALLED_APPS = [
    'django_prometheus',
    'unfold',
    "unfold.contrib.forms",
    'django.forms',
    'django_recaptcha',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'agency', 'customers', 'orders',
    'website', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'website.context_processors.global_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

database_url = os.environ.get('DATABASE_URL')

# Detect if we are running 'manage.py test' or 'pytest'
IS_TESTING = 'test' in sys.argv or 'pytest' in sys.modules

if database_url and not IS_TESTING:
    # CRITICAL: conn_max_age MUST be 0 for Serverless and Supabase connection poolers
    db_from_env = dj_database_url.config(
        default=database_url,
        conn_max_age=0, 
        conn_health_checks=True,
    )
    DATABASES['default'].update(db_from_env)

    # 3. Supabase Transaction Mode Fixes (Requires Port 6543 in your .env)
    if 'postgresql' in DATABASES['default']['ENGINE']:
        DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
        # Optional: Prevents hanging queries from locking up your database
        DATABASES['default']['OPTIONS'] = {
            'options': '-c statement_timeout=30000', 
        }
# If we are on Render, it will use the DATABASE_URL environment variable
#db_from_env = dj_database_url.config(conn_max_age=0, conn_health_checks=True)
#if db_from_env:
#    DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

APPEND_SLASH = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
# ADD THIS TO LOAD YOUR CSS FIXES:
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# This is where collectstatic will dump files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Tells WhiteNoise not to crash the server if a static file is missing
WHITENOISE_MANIFEST_STRICT = False
# Tells WhiteNoise to compress and cache your CSS/JS for faster loading
STORAGES = {
    "default": {
        "BACKEND": "core.storage.VercelBlobStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage" if DEBUG else "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

FORM_RENDERER = "django.forms.renderers.TemplatesSetting"
# ==========================================
# UNFOLD ADMIN UI CONFIGURATION
# ==========================================
UNFOLD = {
    "SITE_TITLE": "Shirdi Hoardings Admin",
    "SITE_HEADER": "Shirdi Hoardings Manager",
    "DASHBOARD_CALLBACK": "core.views.dashboard_callback",

    # This injects our custom CSS to fix the forms
    "STYLES": [
        lambda request: static("css/admin_tweaks.css"),
    ],

    # ==========================================
    # ADDING SIDEBAR ICONS AND GROUPS
    # ==========================================
    "SIDEBAR": {
        "show_search": True, # Adds a global search bar to the menu
        "show_all_applications": True, 
        "navigation": [
            {
                "title": "Inventory & Agency",
                "separator": True, # Adds a clean line above this section
                "items": [
                    {
                        "title": "Hoardings (Products)",
                        "icon": "map", # Material Symbol Icon
                        "link": "/admin/agency/product/",
                    },
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": "/admin/agency/category/",
                    },
                    {
                        "title": "Sub-Categories",
                        "icon": "account_tree",
                        "link": "/admin/agency/subcategory/",
                    },
                    {
                        "title": "Inquiries",
                        "icon": "mail",
                        "link": "/admin/website/inquiry/",
                    },
                    {
                        "title": "Vendor Management",
                        "icon": "payments",
                        "separator": True, # Creates a nice visual divider line
                        "link": "/admin/agency/vendorexpense/",
                    },
                    {
                        "title": "Reports",
                        "icon": "analytics", # Material Symbol Icon
                        "link": "/admin/reports/",
            },
                ],
            },
            {
                "title": "Client Management",
                "separator": True,
                "items": [
                    {
                        "title": "Customers",
                        "icon": "groups", 
                        "link": "/admin/customers/customer/",
                    },
                ],
            },
            {
                "title": "Billing & Timelines",
                "separator": True,
                "items": [
                    {
                        "title": "Invoices",
                        "icon": "receipt_long", 
                        "link": "/admin/orders/invoice/",
                    },
                ],
            },
        ],
    },

    # Defines the blue highlight colors for buttons and form focuses
    "COLORS": {
        "primary": {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6",
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
        },
    },
}


# ==========================================
# GOOGLE RECAPTCHA SETTINGS
# ==========================================
RECAPTCHA_PUBLIC_KEY = '6LcQMTYtAAAAADEbjM4dsGhHEkopYFhV77Ovjyx9'
RECAPTCHA_PRIVATE_KEY = '6LcQMTYtAAAAAALUOkfnFzI6clCEyXK3s6vZGUSd'
# Silences the warning that we are using test keys
SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']
