# Generated by Django 6.0.6 on 2026-06-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Contact person's name", max_length=255)),
                ('gst_number', models.CharField(blank=True, help_text='15-character alphanumeric GSTIN', max_length=15)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total pending amount to be paid', max_digits=12)),
                ('company_name', models.CharField(blank=True, help_text='Legal name for the PDF Bill', max_length=255)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=50000.0, help_text='Max allowed due amount before rejecting new orders', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to blacklist/block this customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
