# Generated by Django 6.0.6 on 2026-07-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=50000.0, help_text='Max allowed due amount before rejecting new orders', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total pending amount to be paid', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
