apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: global-banner-secrets
  labels:
    tier: platform-infrastructure
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1

  # ns restrictions
  conditions:
    - namespaceSelector:
        matchExpressions:
          - key: environment
            operator: In
            values: 
              - production
              - staging
          # block system ns
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
              - kube-system
              - default

