# Generated by Django 6.0.6 on 2026-06-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='mounting_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost for mounting the hoarding', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='printing_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost for printing the flex/vinyl', max_digits=10, null=True),
        ),
    ]
