# Generated by Django 6.0.6 on 2026-06-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Supports HTML for bold, lists, tables, etc.')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the website')),
                ('location_address', models.TextField(blank=True, help_text='Physical address of the hoarding')),
                ('map_coordinates', models.CharField(blank=True, help_text='Lat/Long for Google Maps integration', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_primary', models.BooleanField(default=False, help_text='Check this to make it the main thumbnail')),
                ('alt_text', models.CharField(blank=True, help_text='Good for SEO on the showcase site', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agency.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in feet/meters', max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in feet/meters', max_digits=6)),
                ('stock', models.IntegerField(default=1)),
                ('hsn_code', models.CharField(max_length=20)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=4)),
                ('color', models.CharField(blank=True, help_text='Frame or background color, if applicable', max_length=50)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offline_price', models.DecimalField(decimal_places=2, help_text='Price for walk-in/direct clients', max_digits=10)),
                ('online_price', models.DecimalField(decimal_places=2, help_text='Visible on the showcase website', max_digits=10)),
                ('sku', models.CharField(help_text='Stock Keeping Unit / Unique ID for this specific size', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='agency.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='agency.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.subcategory'),
        ),
    ]
