# Generated by Django 6.0.6 on 2026-06-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='mounting_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost for mounting the hoarding', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='printing_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost for printing the flex/vinyl', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Supports HTML for bold, lists, tables, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='location_address',
            field=models.TextField(blank=True, help_text='Physical address of the hoarding', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='map_coordinates',
            field=models.CharField(blank=True, help_text='Lat/Long for Google Maps integration', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Good for SEO on the showcase site', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, help_text='Frame or background color, if applicable', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=18.0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in feet/meters', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in feet/meters', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='offline_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for walk-in/direct clients', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='online_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Visible on the showcase website', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit / Unique ID for this specific size', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='agency.category'),
        ),
    ]
