# Generated by Django 6.0.6 on 2026-06-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_productvariant_mounting_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Paste a YouTube video link. Used as a fallback if no images are uploaded.', max_length=500, null=True),
        ),
    ]
