# Generated by Django 6.0.6 on 2026-06-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_product_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='mounting_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='printing_price',
        ),
    ]
