# Generated by Django 6.0.6 on 2026-06-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_remove_productvariant_mounting_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(help_text='Name of the vendor or land owner', max_length=255)),
                ('location', models.CharField(help_text='Physical location or hoarding associated with this cost', max_length=255)),
                ('start_date', models.DateField(help_text='When does this vendor contract/booking start?')),
                ('end_date', models.DateField(help_text='When does it end?')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Total cost to be paid to the vendor', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor Expense',
                'verbose_name_plural': 'Vendor Expenses',
                'ordering': ['-start_date'],
            },
        ),
    ]
