# Generated by Django 6.0.6 on 2026-06-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_vendorexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorexpense',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost to be paid to the vendor', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorexpense',
            name='end_date',
            field=models.DateField(blank=True, help_text='When does it end?', null=True),
        ),
        migrations.AlterField(
            model_name='vendorexpense',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location or hoarding associated with this cost', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorexpense',
            name='start_date',
            field=models.DateField(blank=True, help_text='When does this vendor contract/booking start?', null=True),
        ),
    ]
